name: Parser tests

on:
  push:
    branches:
      main
  pull_request:

jobs:
  test_parser:
    strategy:
      fail-fast: false
    name: Testing
    runs-on: ubuntu-latest
    env:
      CC: clang
    steps:
      - name: Prepare tree-sitter
        uses: actions/checkout@v2
        with:
          repository: tree-sitter/tree-sitter

      - name: Prepare tree-sitter-norg-table
        uses: actions/checkout@v2
        with:
          path: test/fixtures/grammars/norg_table

      - name: Install tree-sitter CLI
        run: |
          cd test/fixtures/grammars/norg_table
          npm install tree-sitter-cli

      - name: Run tests
        run: |
          cd test/fixtures/grammars/norg_table
          ./node_modules/tree-sitter-cli/tree-sitter test
